### ISSUE TITLE
Error in console when hit tab and some emojis dont show up

### ISSUE THREAD

**Issue by Trnrr** [pie-flavor/mcmoji#1]
Not sure if this is a bug or you just haven't done it yet. When you type `:` and then hit `tab`, it throws an error in console. https://gist.github.com/Trnrr/d89900306235c283e0e330d36c0e6047

Also while I was trying to see what emojis you could do I found some that don't work. I'm not sure if I'm using the wrong file or if it's a bug or something. I was trying some of the words in `alternates.json` and some worked and some didn't work. http://puu.sh/DuEvJ/a8dae52761.jpg

**Comment by Trnrr** [comment]
I just realized I'm using build 3616 of spongeforge and that's quite outdated. I leave for vacation on Wednesday and if I have time before that I will test on the newer build. But I still have the other issue.

**Comment by Trnrr** [comment]
I just updated to build spongeforge-1.12.2-2825-7.1.6-RC3713 and it still doesn't work when I hit tab.

When the server starts it shows this message: https://gist.github.com/Trnrr/2c629e8e608d6572a7b29dd653a103ea
When I try to hit tab: https://gist.github.com/Trnrr/53cf44b29962b2da63054420ccf48c52

**Comment by pie-flavor** [comment]
Try deleting the configuration folder and letting it regenerate.

**Comment by Trnrr** [comment]
Thanks, I will try that once I get home from vacation.

**Comment by pie-flavor** [comment]
Is this still an issue?

**Comment by Trnrr** [comment]
I apologize, some stuff came up and I never got around to it. I'm using a newer version of sponge/forge now so the issue is probably fixed. I will let you know if otherwise though.
